<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>$(RootNamespace).Cli</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Kurio.Core\Kurio.Core.csproj"/>
        <ProjectReference Include="..\KuriousLabs.Kurio.ServiceDefaults\KuriousLabs.Kurio.ServiceDefaults.csproj"/>
    </ItemGroup>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

</Project>
