<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>$(RootNamespace).Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kurio.Core.Tests"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
    <PackageReference Include="Microsoft.Extensions.Http"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
    <PackageReference Include="Polly"/>
    <PackageReference Include="Polly.Extensions"/>
    <PackageReference Include="System.Threading.RateLimiting"/>
  </ItemGroup>

</Project>
